### ISSUE TITLE
Missing a link in PDF

### ISSUE THREAD

**Issue by knorrrr** [pibiger-tech/PU2CANFD-C#1]
There is a no link to "chapter 5 Appendix A-ID Setting Reference".
I want to know how to deactivate a 120 Ohm term resistor in PU2CANFD.
![image](https://github.com/pibiger-tech/PU2CANFD-C/assets/99851410/40b149b5-5eca-4271-9488-30f6cf932834)
https://github.com/pibiger-tech/PU2CANFD-C/blob/main/Manual/SavvyCAN%20Hardware%20Manual.pdf

**Comment by anonymouslojz** [comment]
Would you mind leave your email?

**Comment by knorrrr** [comment]
kunotomoki61@gmail.com

**Comment by knorrrr** [comment]
Thanks!
